name: Build and Release on push

on:
  push:    # срабатывает при каждом пуше (коммите)

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Detect project (.csproj)
        id: detect
        shell: pwsh
        run: |
          $proj = Get-ChildItem -Path . -Filter *.csproj -Recurse | Select-Object -First 1
          if (-not $proj) {
            Write-Error "No .csproj found in repository"
            exit 1
          }
          $rel = $proj.FullName.Substring($PWD.Path.Length + 1) -replace '\\','/'
          echo "project_path=$rel" >> $GITHUB_OUTPUT
          Write-Host "Detected project: $rel"

      - name: Make short SHA and tag name
        id: taggen
        shell: pwsh
        run: |
          $short = $env:GITHUB_SHA.Substring(0,7)
          $tag = "ci-$short"
          echo "tag_name=$tag" >> $GITHUB_OUTPUT
          Write-Host "Using tag: $tag"

      - name: Restore dependencies
        shell: pwsh
        run: dotnet restore "${{ steps.detect.outputs.project_path }}"

      - name: Publish single-file (Release)
        shell: pwsh
        env:
          RUNTIME: win-x64
          TARGET_FRAMEWORK: net9.0-windows
          SELF_CONTAINED: true
        run: |
          dotnet publish "${{ steps.detect.outputs.project_path }}" -c Release -r $env:RUNTIME -f $env:TARGET_FRAMEWORK -p:PublishSingleFile=true -p:SelfContained=$env:SELF_CONTAINED -p:PublishTrimmed=false -o ./publish

      - name: Show publish folder contents (debug)
        shell: pwsh
        run: |
          if (Test-Path ./publish) {
            Get-ChildItem -Path ./publish -Recurse | Format-Table -AutoSize
          } else {
            Write-Error "Publish folder not found"
            exit 1
          }

      - name: Create zip of publish folder
        shell: pwsh
        run: |
          Compress-Archive -Path ./publish/* -DestinationPath ./publish/OnScreen-GIF-WPF.zip -Force

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.taggen.outputs.tag_name }}
          release_name: ${{ steps.taggen.outputs.tag_name }}
          body: "Automated build for commit ${{ github.sha }}"
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload release asset (zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/OnScreen-GIF-WPF.zip
          asset_name: OnScreen-GIF-WPF.zip
          asset_content_type: application/zip
